# Generated by Django 4.1.5 on 2023-02-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
